title: "La Fortuna website"
email: slayerofallx@gmail.com
timezone: UTC
website: 192.168.56.106:4000
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: slayerofallx
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
emailtok: xeqdjejb
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-G8J5CWCG0L 


# Authors
authors:
  slayerofallx:
    name: Slayerofallx 
    display_name: Slayerofallx 
    avatar: 'assets/images/slayerofallx.png'
    email: slayerofallx@gmail.com
    web: https://wilderh.me/
    twitter: https://twitter.com/
    description: "My name is Slayerofall, creator of this blog. This blog is aimed to show some of the spots of the town where I grew up"

# Social
social:
  instagram: https://www.instagram.com/
  facebook: https://www.facebook.com/
  twitter: https://twitter.com/

jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
  homepage: "pages"

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
